{
 "title": "Vault / Overview",
 "tags": [
  "hashicorp",
  "vault-mixin",
  "alpha"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(vault_core_active, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Leases",
   "type": "stat",
   "description": "The total number of leases eligible for eventual expiry.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(vault_expire_num_leases{job=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "table",
   "description": "Number of un-expired and un-revoked tokens available for use in the token store. Updated every 10 minutes.",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(vault_token_count{job=~\"$cluster\"}[15m])"
    }
   ]
  },
  {
   "title": "Identity Entities",
   "type": "table",
   "description": "The number of identity entity aliases (per namespace) currently stored in Vault.",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(vault_identity_entity_count{job=~\"$cluster\"}[20m])"
    }
   ]
  },
  {
   "title": "Mounts",
   "type": "table",
   "description": "Number and size of mounts in the given mount table across all namespaces.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(last_over_time(vault_core_mount_table_num_entries{job=~\"$cluster\"}[$__range])) without(cluster,host,instance,job)"
    },
    {
     "expr": "max(last_over_time(vault_core_mount_table_size{job=~\"$cluster\"}[$__range])) without(cluster,host,instance,job)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Vault non-login requests per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(vault_core_handle_request_count{job=~\"$cluster\"}[$__rate_interval])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Performance Replication Role",
   "type": "stat",
   "description": "Current role in a performance replicationset. If enabled, primary or secondary will be displayed.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(vault_core_replication_performance_primary{job=\"$cluster\"}) by (__name__) > 0",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "max(vault_core_replication_performance_secondary{job=\"$cluster\"}) by (__name__) > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Autopilot Cluster Health",
   "type": "timeseries",
   "description": "Indicates whether all nodes in the cluster are healthy, including non-voting members.",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vault_autopilot_healthy{job=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Autopilot Node Health",
   "type": "stat",
   "description": "Latest node status summarized for all nodes in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(vault_autopilot_node_healthy{job=\"$cluster\"} != 0)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "count(vault_autopilot_node_healthy{job=\"$cluster\"} == 0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Nodes being scraped for metrics.",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(up{job=\"$cluster\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Disaster Replication Role",
   "type": "stat",
   "description": "Current role in a disaster recovery replicationset. If enabled, primary or secondary is displayed.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(vault_core_replication_dr_primary{job=\"$cluster\"}) by (__name__) > 0",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "max(vault_core_replication_dr_secondary{job=\"$cluster\"}) by (__name__) > 0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Performance Standbys",
   "type": "stat",
   "description": "The number of performance standby nodes in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(vault_core_performance_standby{job=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Seal Status",
   "type": "stat",
   "description": "Latest seal status summarized for all nodes in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(vault_core_unsealed{job=\"$cluster\"} != 0)",
     "legendFormat": "Unsealed"
    },
    {
     "expr": "count(vault_core_unsealed{job=\"$cluster\"} == 0)",
     "legendFormat": "Sealed"
    }
   ]
  }
 ]
}